spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: XXXXXXXXX
    password: XXXXXXXXX
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: 'true'
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: XXXXXXXXXX
    password: XXXXXXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true