spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/nnewdbb
    password: Mery?%32
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    spring:
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher