spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/devdb
    password: Mery?%32
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'


